### ISSUE TITLE
[BUG] For MIND small dataset utils, it can not download.

### ISSUE THREAD

**Issue by Codle** [microsoft/recommenders#1203]
### In which platform does it happen?
Local Host: Ubuntu 18.04

### How do we replicate the issue?
use example/00_quick_start/lstur_MIND.ipynb and change the MIND_TYPE to 'small'.

### Expected behavior (i.e. solution)
run this demo

### Other Comments

Could you please check this file name is correct?
https://github.com/microsoft/recommenders/blob/837b8081a4421e144f2bc05ba949c5ac6c52320f/reco_utils/recommender/newsrec/newsrec_utils.py#L358

In this code, the file named "MINDsma_utils.zip" may be not correct. I also tested "MINDsmall_utils.zip" but it can't download either.

**Comment by wutaomsft** [comment]
@yjw1029 can you take a look?

**Comment by shainaraza** [comment]
you may want to download to a specific location , I did that way and then you can see the data
for example I did like this in NAML
import sys
[sys.path.append("/content/drive/My Drive/Recommenders")
from reco_utils.recommender.deeprec.deeprec_utils import download_deeprec_resources 
from reco_utils.recommender.newsrec.newsrec_utils import prepare_hparams
from reco_utils.recommender.newsrec.models.naml import NAMLModel
from reco_utils.recommender.newsrec.io.mind_all_iterator import MINDAllIterator
from reco_utils.recommender.newsrec.newsrec_utils import get_mind_data_set
import papermill as pm
from tempfile import TemporaryDirectory
import tensorflow as tf
import os

print("System version: {}".format(sys.version))
print("Tensorflow version: {}".format(tf.__version__))
](url)

**Comment by miguelgfierro** [comment]
this #1218 should fix the issue

**Comment by wutaomsft** [comment]
Reopening.  The issue still exists when you change the MIND_type to "small".

**Comment by wutaomsft** [comment]
@Leavingseason could you take a look?  Looks https://recodatasets.blob.core.windows.net/newsrec/MINDsmall_utils.zip is missing.  Both https://recodatasets.blob.core.windows.net/newsrec/MINDdemo_utils.zip and https://recodatasets.blob.core.windows.net/newsrec/MINDlargel_utils.zip are there so everything is fine if MIND_type is set to "demo" or "large".  However, MINDsmall_utils.zip is missing.

**Comment by wutaomsft** [comment]
The files should be there now @Codle .  Code and test update will take a few days but you should be unblocked now.

**Comment by bestpredicts** [comment]
still  can not download  https://mind201910small.blob.core.windows.net/release/MINDsma_utils.zip

**Comment by wutaomsft** [comment]
there was a typo in the url in the code that was fixed in staging.  Should be in master soon.  The correct filename is MINDsmall_utils.zip.

**Comment by wutaomsft** [comment]
closed as fix is in master. https://github.com/microsoft/recommenders/pull/1229.  utils files are also uploaded.
