### ISSUE TITLE
[BUG] Can not download MIND_small dataset

### ISSUE THREAD

**Issue by hannlp** [microsoft/recommenders#1221]
### Description
Prepare Parameters¶
epochs=6
seed=40
MIND_type = 'small'

Download and load data¶
data_path = tmpdir.name
​
train_news_file = os.path.join(data_path, 'train', r'news.tsv')
train_behaviors_file = os.path.join(data_path, 'train', r'behaviors.tsv')
valid_news_file = os.path.join(data_path, 'valid', r'news.tsv')
valid_behaviors_file = os.path.join(data_path, 'valid', r'behaviors.tsv')
wordEmb_file = os.path.join(data_path, "utils", "embedding.npy")
userDict_file = os.path.join(data_path, "utils", "uid2index.pkl")
wordDict_file = os.path.join(data_path, "utils", "word_dict.pkl")
yaml_file = os.path.join(data_path, "utils", r'npa.yaml')
​
mind_url, mind_train_dataset, mind_dev_dataset, mind_utils = get_mind_data_set(MIND_type)
​
if not os.path.exists(train_news_file):
    download_deeprec_resources(mind_url, os.path.join(data_path, 'train'), mind_train_dataset)
    
if not os.path.exists(valid_news_file):
    download_deeprec_resources(mind_url, \
                               os.path.join(data_path, 'valid'), mind_dev_dataset)
if not os.path.exists(yaml_file):
    download_deeprec_resources(r'https://recodatasets.blob.core.windows.net/newsrec/', \
                               os.path.join(data_path, 'utils'), mind_utils)
100%|██████████| 51.7k/51.7k [07:39<00:00, 113KB/s] 
100%|██████████| 30.2k/30.2k [02:47<00:00, 180KB/s] 
100%|██████████| 1.00/1.00 [00:00<00:00, 485KB/s]
---------------------------------------------------------------------------
BadZipFile                                Traceback (most recent call last)
<ipython-input-3-6f6b714521cb> in <module>
     20 if not os.path.exists(yaml_file):
     21     download_deeprec_resources(r'https://recodatasets.blob.core.windows.net/newsrec/', \
---> 22                                os.path.join(data_path, 'utils'), mind_utils)

~/Lab/Recommenders/reco_utils/recommender/deeprec/deeprec_utils.py in download_deeprec_resources(azure_container_url, data_path, remote_resource_name)
    507     remote_path = azure_container_url + remote_resource_name
    508     maybe_download(remote_path, remote_resource_name, data_path)
--> 509     zip_ref = zipfile.ZipFile(os.path.join(data_path, remote_resource_name), "r")
    510     zip_ref.extractall(data_path)
    511     zip_ref.close()

~/anaconda3/envs/reco_base/lib/python3.6/zipfile.py in __init__(self, file, mode, compression, allowZip64)
   1129         try:
   1130             if mode == 'r':
-> 1131                 self._RealGetContents()
   1132             elif mode in ('w', 'x'):
   1133                 # set the modified flag so central directory gets written

~/anaconda3/envs/reco_base/lib/python3.6/zipfile.py in _RealGetContents(self)
   1196             raise BadZipFile("File is not a zip file")
   1197         if not endrec:
-> 1198             raise BadZipFile("File is not a zip file")
   1199         if self.debug > 1:
   1200             print(endrec)

BadZipFile: File is not a zip file

### In which platform does it happen?
Linux jupyter notebook with reco_base environment 

### How do we replicate the issue?
Create a conda environment for reco_base
run Recommenders/examples/00_quick_start/npa_MIND.ipynb in jupyter notebook with these parameters :
**Prepare Parameters¶**
epochs=6
seed=40
MIND_type = 'small'

### Expected behavior (i.e. solution)
the "Download and load data" block can pass successfully

**Comment by miguelgfierro** [comment]
this https://github.com/microsoft/recommenders/pull/1218 should fix the issue

**Comment by wutaomsft** [comment]
Reopening as that issue is not solved. @Leavingseason could you respond to this as well?

**Comment by wutaomsft** [comment]
The file should be there now @hannlp .  Code and test update will take a few days but you should be unblocked now.

**Comment by wutaomsft** [comment]
closed as fix is in master. https://github.com/microsoft/recommenders/pull/1229.  utils files are also uploaded.
